### PR TITLE
disabled modules for the css extractions

### PR DESCRIPTION
**Pull request by smashingpat**
you can still use the module behaviour by
adding :local infront of css classnames

### CODE REVIEW

**Review by ivo-toby — APPROVED** [review]

**Comment by FranklinWaller** [comment]
I think something went wrong with the versioning since these are breaking changes. Now all projects that has for example '^1.0.8' will get v1.0.13 which is not compatible at all with v1.0.8 (Even though semver suggests it does)

**Comment by smashingpat** [comment]
Oh that's not good as this can be a breaking feature for some targets, should've been something like `v1.1.0`

**Comment by FranklinWaller** [comment]
Well all plugins/targets that use the 1.0.x are now broken 😅  (For people that haven't checked out the project yet)

**Comment by smashingpat** [comment]
Although are they really? The css-modules should only take effect if a cssFilename is specified in the gulpfile config

**Comment by FranklinWaller** [comment]
Yes you are correct, so it's mostly the standardUI and targets

**Comment by smashingpat** [comment]
Only if the target specifies that the css file should be created in its `gulpfile.js`, by default it would still inject the css through the `style-loader`

**Comment by FranklinWaller** [comment]
Sadly something still goes wrong with that, because my gulpfile doesn't have such configuration but still throws this error:

```
ERROR in ./~/@meisterplayer/plugin-standardui/src/sass/meister.scss
Module build failed: 
@import "lib/mixins";
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /Users/f.waller/Documents/Teams/Meister/targets/Rtl/node_modules/@meisterplayer/plugin-standardui/src/sass/meister.scss (line 1, column 1)
 @ ./~/@meisterplayer/plugin-standardui/index.js 7:15-49
 @ ./src/js/MeisterPlayer.js
 @ ./index.js
 @ multi ./index.js
```

Downgrading to v1.0.8 fixes this issue.

**Comment by smashingpat** [comment]
Ah you're correct, but from where is the `lib/mixins` being loaded?

**Comment by FranklinWaller** [comment]
As just discussed we will revert the changes and create a new version (v1.0.14) Where the changes are back to normal. Then there will be a v1.1.0 where these changes are added

**Pull request merged**
